### PR TITLE
Sils/gmt

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils1297** [comment]
Comment on 9f5337aa85ce8890465883a9340a26f795d114fc, file antbs/antbs.py, line 59.

C0411 - standard import "import utils.pagination" comes before "import requests"

*PyLintBear, severity INFO, section `python`.*

**Comment by sils1297** [comment]
Comment on 9f5337aa85ce8890465883a9340a26f795d114fc, file antbs/database/transaction.py, line 39.

C0411 - standard import "import utils.docker_util as docker_util" comes before "from .base_objects import RedisHash, db"

*PyLintBear, severity INFO, section `python`.*

**Comment by sils1297** [comment]
Comment on 605ca199d4555f9302e6cbd7338057a420c2eb5e, file antbs/database/transaction.py, line 39.

C0411 - external import "import utils.docker_util as docker_util" comes before "from .base_objects import RedisHash, db"

*PyLintBear, severity INFO, section `python`.*

**Comment by sils1297** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91, file antbs/iso.py, line 41.

C0411 - standard import "import utils.sign_pkgs as sign" comes before "import requests"

*PyLintBear, severity INFO, section `python`.*

**Comment by sils1297** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91.

Shortlog of HEAD commit contains a period at end.

*GitCommitBear, severity NORMAL, section `commits`.*

**Comment by sils1297** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91, file antbs/database/transaction.py, line 39.

C0411 - standard import "import utils.docker_util as docker_util" comes before "from pygments import highlight"

*PyLintBear, severity INFO, section `python`.*

**Comment by sils1297** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91, file antbs/iso.py, line 41.

C0411 - standard import "import utils.sign_pkgs as sign" comes before "import requests"

*PyLintBear, severity INFO, section `python`.*

**Comment by sils1297** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91.

Shortlog of HEAD commit contains a period at end.

*GitCommitBear, severity NORMAL, section `commits`.*

**Comment by sils** [comment]
Comment on 9f5337aa85ce8890465883a9340a26f795d114fc, file antbs/database/transaction.py, line 39.

C0411 - standard import "import utils.docker_util as docker_util" comes before "from pygments import highlight"

_PyLintBear, severity INFO, section `python`._

**Comment by sils** [comment]
Comment on 605ca199d4555f9302e6cbd7338057a420c2eb5e, file antbs/database/transaction.py, line 39.

C0411 - external import "import utils.docker_util as docker_util" comes before "from .base_objects import RedisHash, db"

_PyLintBear, severity INFO, section `python`._

**Comment by sils** [comment]
Comment on 605ca199d4555f9302e6cbd7338057a420c2eb5e, file antbs/iso.py, line 41.

C0411 - standard import "import utils.sign_pkgs as sign" comes before "import requests"

_PyLintBear, severity INFO, section `python`._

**Comment by sils** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91, file antbs/antbs.py, line 59.

C0411 - standard import "import utils.pagination" comes before "import requests"

_PyLintBear, severity INFO, section `python`._

**Comment by sils** [comment]
Comment on 71226b1c8f63087ea0bf4ca5278cc15e4d6c2e91.

Shortlog of HEAD commit contains a period at end.

_GitCommitBear, severity NORMAL, section `commits`._

**Pull request closed without merging**
